### ISSUE TITLE
jirasearch.mikemccandless.com is not indexing new issues

### ISSUE THREAD

**Issue by dsmiley** [mikemccand/luceneserver#6]
Thanks for running jirasearch!  Firstly, my apologies if I'm reporting this the wrong way; maybe I should have emailed the Lucene dev list?  Or just email you directly as this is not an ASF project?

I can't find a recent JIRA issue:

http://jirasearch.mikemccandless.com/search.py?chg=new&text=SOLR-11866

While I'm chatting about jirasearch... the biggest pain point I have in using it is that CamelCase like Java class names are not being treated as a phrase.

**Comment by mikemccand** [comment]
Very odd; I'm not sure why that issue is missing from jirasearch index!

And yes this is the right place to open an issue but I obviously don't check frequently enough so feel free to ping me directly too.

CamelCase names are split into separate tokens which should then be in adjacent positions and should in fact answer to PhraseQuery.  Are you saying "CamelCase" as a query does not match the corresponding java class name in issues?

**Comment by dsmiley** [comment]
Maybe the problem is that the Security Level is set, even though it's Public.  See a recent dev list message from Rafalovich & Cassandra: "Sanity check: JIRA search discrepancy when logged-in/anon"

RE camel case... if I explicitly use a quotes then the phrase works.  But if I simply use CamelCase in the query then it does not query as a phrase.  If we were talking Solr configuration, this would be an "autoGeneratePhraseQueries" setting on the field type.  For english text this is a problem since as a user I see one word in my query.

**Comment by dsmiley** [comment]
Yeah that's it.  The security level was cleared and it's now in jirasearch.
